json.extract! @user,
              :id,
              :personal_name,
              :email,
              :company_name,
              :industry,
              :locale,
              :female_founder,
              :ethnic_founder,
              :capital_goal,
              :fundraising_stage,
              :created_at,
              :updated_at
