default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: 5

development:
  <<: *default
  database: website-covize-pitch-alerts_development
  username: root
  password: root
  host: localhost

test:
  <<: *default
  database: website-covize-pitch-alerts_test
  username: root
  password: root
  host: localhost

production:
  <<: *default
  database: website-covize-pitch-alerts_production
  username: website-covize-pitch-alerts
  password: <%= ENV['WEBSITE-COVIZE-PITCH-ALERTS_DATABASE_PASSWORD'] %>
