# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Faker::Config.locale = 'en-US'

100.times do |i|
  PitchEvent.create(
      event_name: Faker::Lorem.word,
      org_name: Faker::Company.name,
      address_1: Faker::Address.street_address,
      address_2: Faker::Address.building_number,
      city: Faker::Address.city,
      state: Faker::Address.state,
      zip: Faker::Address.zip,
      locale: [
          'Anchorage, AK',
          'Birmingham, AL',
          'Little Rock, AR',
          'Phoenix, AZ',
          'Tucson, AZ',
          'Los Angeles, CA',
          'San Francisco, CA',
          'Riverside, CA',
          'San Diego, CA',
          'Sacramento, CA',
          'San Jose, CA',
          'Fresno, CA',
          'Denver, CO',
          'Bridgeport, CT',
          'Hartford, CT',
          'Wilmington, DE',
          'Jacksonville, FL',
          'Miami, FL',
          'Orlando, FL',
          'Tampa, FL',
          'Atlanta, GA',
          'Urban Honolulu, HI',
          'Des Moines, IA',
          'Boise, ID',
          'Chicago, IL',
          'Indianapolis, IN',
          'Wichita, KA',
          'Louisville, KY',
          'New Orleans, LA',
          'Boston, MA',
          'Worcester, MA',
          'Baltimore, MD',
          'Portland, ME',
          'Detroit, MI',
          'Grand Rapids, MI',
          'Minneapolis, MN',
          'Kansas City, MO',
          'St. Louis, MO',
          'Jackson, MS',
          'Billings, MT',
          'Charlotte, NC',
          'Raleigh, NC',
          'Fargo, ND',
          'Omaha, NE',
          'Manchester, NH',
          'Newark, NJ',
          'Albuquerque, NM',
          'Las Vegas, NV',
          'Buffalo, NY',
          'New York, NY',
          'Rochester, NY',
          'Cincinnati, OH',
          'Cleveland, OH',
          'Columbus, OH',
          'Oklahoma City, OK',
          'Tulsa, OK',
          'Portland, OR',
          'Philadelphia, PA',
          'Pittsburgh, PA',
          'Providence, RI',
          'Columbia, SC',
          'Sioux Falls, SD',
          'Memphis, TN',
          'Nashville, TN',
          'Austin, TX',
          'Dallas, TX',
          'Houston, TX',
          'San Antonio, TX',
          'Salt Lake City, UT',
          'Richmond, VA',
          'Virginia Beach, VA',
          'Burlington, VT',
          'Seattle, WA',
          'Milwaukee, WI',
          'Charleston, WV',
          'Cheyenne, WY',
          'Washington D.C., Washington D.C.'
      ].sample,
      event_start: Faker::Time.between(5.days.from_now, 7.days.from_now).strftime("%m/%d/%Y %H:%M"),
      event_end: Faker::Time.between(7.days.from_now, 8.days.from_now).strftime("%m/%d/%Y %H:%M"),
      registration_deadline: Faker::Time.between(Time.now, 5.days.from_now).strftime("%m/%d/%Y %H:%M"),
      detail_link: Faker::Internet.url,
      contact_name: Faker::Name.name,
      contact_number: Faker::PhoneNumber.cell_phone,
      contact_email: Faker::Internet.email,
      local: [true, false].sample,
      national: [true, false].sample,
      female_founder: [true, false].sample,
      ethnic_founder: [true, false].sample,
      industry: ["technology", "education", "medical", "entertainment", "automotive"].sample,
      latitude: Faker::Address.latitude,
      longitude: Faker::Address.longitude
  )
end